### ISSUE TITLE
BOM Caps

### ISSUE THREAD

**Issue by KeLaiFu** [daanklijn/lmnc-envelope-generator#1]
The BOM only seems to list 2 caps (C1/2) but the PCB has 8. Looking at the schematic, all the additonal ones are on the same 2 lines on opamp pins. Is this the working layout? I have never seen anyone put multiple caps in one place like that, so I wondered if it was an error?

**Comment by daanklijn** [comment]
Hey KeLaiFu! It indeed seemed that there were still some old BOM and POS files in the repo. I have updated them. Thanks for letting me know!
